@URL = {{$dotenv API_URL}}

### Obtener todos los invitados
GET {{URL}}/invitados

### Obtener invitado por id
GET {{URL}}/invitados/c3677952-e31d-4541-8c78-8181f669bbc3

### Confirmar asistencia
PUT {{URL}}/invitados/c3677952-e31d-4541-8c78-8181f669bbc3

{
  "confirmado": false,
  "asistentes": 0
}
